### ISSUE TITLE
Myjobs for residents and service providers

### ISSUE THREAD

**Issue by AdavjeetBhangu** [pahulpreet-dev/Dooramo#2]
Adding Myjobs tab for resident to view history of all previously requested services wheres service provider can view list with history of all previous pending and completed services.

**Comment by haocencol** [comment]
Write as a story and disaggregate into tasks.  I'm presuming that this issue is not simply to add a tab.

**Comment by haocencol** [comment]
Is this issue done yet?

**Comment by AdavjeetBhangu** [comment]
Yes it is complete.

**Comment by pahulpreet-dev** [comment]
I encountered a problem in Android Studio where my commits where not being pushed to the GitHub. The problem was that my HEAD went into the detached state while doing some experiments when learning the Git. I solved the issue by getting help from stackoverflow from the link below. 
https://stackoverflow.com/questions/5772192/how-can-i-reconcile-detached-head-with-master-origin
After pushing the code, I am closing this issue and hence the milestone.
